DROP DATABASE IF EXISTS globes0;
CREATE DATABASE globes0;
\c globes0;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM globe.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM globe.usr;

DROP DATABASE IF EXISTS local0s0;
CREATE DATABASE local0s0;
\c local0s0;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM local0.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM local0.usr;

DROP DATABASE IF EXISTS local0s1;
CREATE DATABASE local0s1;
\c local0s1;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM local0.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM local0.usr;