CREATE SCHEMA IF NOT EXISTS globes0;
USE globes0;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM globe.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM globe.usr;

CREATE SCHEMA IF NOT EXISTS local0s0;
USE local0s0;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM local0.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM local0.usr;

CREATE SCHEMA IF NOT EXISTS local0s1;
USE local0s1;
CREATE TABLE IF NOT EXISTS usr_idx AS SELECT * FROM local0.usr_idx;
CREATE TABLE IF NOT EXISTS usr AS SELECT * FROM local0.usr;